if(isDedicated)then{
ctrlActivate((findDisplay 12)displayCtrl 107);
setTerrainGrid 50;setShadowDistance 0;setViewDistance _vDist;setObjectViewDistance _vDist;enableEnvironment false;
if(isClass(configFile>>"CfgPatches">>"task_force_radio"))then{
activateAddons["task_force_radio","task_force_radio_items"];tf_no_auto_long_range_radio=true;tf_same_sw_frequencies_for_side=true;};
//if(isClass(configFile>>"CfgPatches">>"acre_main"))then{
//activateAddons["acre_api","acre_game","acre_main","acre_sys_antenna","acre_sys_attenuate","acre_sys_components","acre_sys_core","acre_sys_data","acre_sys_debug","acre_sys_fonts","acre_sys_gui","acre_sys_io","acre_sys_fonts","acre_sys_list","acre_sys_modes","acre_sys_prc117f","acre_sys_prc148","acre_sys_prc152","acre_sys_prc343","acre_sys_prc77","acre_sys_radio","acre_sys_retrans","acre_sys_rpc","acre_sys_server","acre_sys_signal","acre_sys_sounds","acre_sys_sync"];};
if(isClass(configFile>>"cfgPatches">>"ace_common"))then{
activateAddons["ace_advanced_ballistics","ace_ai","ace_aircraft","ace_apl","ace_atragmx","ace_attach","ace_backpacks","ace_ballistics","ace_captives","ace_cargo","ace_common","ace_concertina_wire","ace_dagr","ace_difficulties","ace_disarming","ace_disposable","ace_dragging","ace_explosives","ace_fastroping","ace_fcs","ace_finger","ace_flashlights","ace_flashsuppressors","ace_fonts","ace_frag","ace_gestures","ace_gforces","ace_goggles","ace_grenades","ace_hearing","ace_hitreactions","ace_huntir","ace_interact_menu","ace_interaction","ace_inventory","ace_javelin","ace_kestrel4500","ace_laser","ace_laser_selfdesignate","ace_laserpointer","ace_logistics_uavbattery","ace_logistics_wirecutter","ace_magazinerepack","ace_main","ace_map","ace_map_gestures","ace_maptools","ace_markers","ace_medical","ace_medical_menu","ace_microdagr","ace_missileguidance","ace_missionmodules","ace_mk6mortar","ace_modules","ace_movement","ace_mx2a","ace_nametags","ace_nightvision","ace_noidle","ace_noradio","ace_norearm","ace_optics","ace_optionsmenu","ace_overheating","ace_overpressure","ace_parachute","ace_rangecard","ace_realisticnames","ace_rearm","ace_recoil","ace_refuel","ace_recoil","ace_reload","ace_reloadlaunchers","ace_repair","ace_respawn","ace_safemode","ace_sandbag","ace_scopes","ace_sitting","ace_slideshow","ace_smallarms","ace_spectator","ace_spottingscope","ace_switchunits","ace_tacticalladder","ace_tagging","ace_thermals","ace_trenches","ace_tripod","ace_ui","ace_vector","ace_vehiclelock","ace_vehicles","ace_viewdistance","ace_weaponselect","ace_weather","ace_winddeflection","ace_yardage450","ace_zeus"];};
if(isClass(configFile>>"cfgPatches">>"Taliban_fighters"))then{
activateAddons["Taliban_Fighters"];};
if(isClass(configFile>>"cfgPatches">>"CUP_Weapons_WeaponsCore"))then{
activateAddons["CUP_BaseConfigs","CUP_BaseData","CUP_Weapons_AA12","CUP_Weapons_AK","CUP_Weapons_AmmoBoxes","CUP_Weapons_Ammunition","CUP_Weapons_AS50","CUP_Weapons_AWM","CUP_Weapons_Backpacks","CUP_Weapons_Bizon","CUP_Weapons_C7","CUP_Weapons_Colt1911","CUP_Weapons_Compact","CUP_Weapons_Compatibility","CUP_Weapons_Curator","CUP_Weapons_CZ750","CUP_Weapons_CZ805","CUP_Weapons_Duty","CUP_Weapons_DMR","CUP_Weapons_East_Attachments","CUP_Weapons_Evo","CUP_Weapons_FNFAL","CUP_Weapons_G36","CUP_Weapons_Glock17","CUP_Weapons_GrenadeLaunchers","CUP_Weapons_Grenades","CUP_Weapons_Huntingrifle","CUP_Weapons_Igla","CUP_Weapons_Items","CUP_Weapons_Javelin","CUP_Weapons_KSVK","CUP_Weapons_L7A2","CUP_Weapons_L85","CUP_Weapons_L110","CUP_Weapons_LeeEnfield","CUP_Weapons_M9","CUP_Weapons_M14","CUP_Weapons_M14_DMR","CUP_Weapons_M16","CUP_Weapons_M24","CUP_Weapons_M47","CUP_Weapons_M60E4","CUP_Weapons_M107","CUP_Weapons_M110","CUP_Weapons_M136","CUP_Weapons_M240","CUP_Weapons_M249","CUP_Weapons_M1014","CUP_Weapons_MAAWS","CUP_Weapons_Makarov","CUP_Weapons_Metis_AT_13","CUP_Weapons_MicroUZI","CUP_Weapons_Mk48","CUP_Weapons_MP5","CUP_Weapons_NLAW","CUP_Weapons_NVG","CUP_Weapons_PB_6P9","CUP_Weapons_Phantom","CUP_Weapons_PK","CUP_Weapons_Pods","CUP_Weapons_Put","CUP_Weapons_Revolver","CUP_Weapons_RPG7","CUP_Weapons_RPG18","CUP_Weapons_SA58","CUP_Weapons_SA61","CUP_Weapons_Saiga12K","CUP_Weapons_SCAR","CUP_Weapons_SMAW","CUP_Weapons_StaticWeapons","CUP_Weapons_Stinger","CUP_Weapons_Strela_2","CUP_Weapons_SVD","CUP_Weapons_UK59","CUP_Weapons_VehicleWeapons","CUP_Weapons_VSS","CUP_Weapons_WeaponsCore","CUP_Weapons_WeaponsData","CUP_Weapons_West_Attachments","CUP_Weapons_XM8"];};
if(isClass(configFile>>"cfgPatches">>"CUP_Creatures_People_Core"))then{
activateAddons["CUP_BaseConfigs","CUP_BaseData","CUP_Creatures_People_Core","CUP_Creatures_People_Civil_Chernarus","CUP_Creatures_People_Military_ACR","CUP_Creatures_People_Military_BAF","CUP_Creatures_People_Military_DummyInfantrySet","CUP_Creatures_People_Military_Germany","CUP_Creatures_People_Military_NAPA","CUP_Creatures_People_Military_PMC","CUP_Creatures_People_Military_RACS","CUP_Creatures_People_Military_SLA","CUP_Creatures_People_Military_Taki","CUP_Creatures_People_Military_TakiInsurgents","CUP_Creatures_People_Military_USMC"];};
if((isClass(configFile>>"cfgPatches">>"CUP_WheeledVehicles_Core"))&&{(isClass(configFile>>"cfgPatches">>"CUP_BaseConfigs"))})then{
activateAddons["CUP_AirVehicles_AH6","CUP_AirVehicles_AN2","CUP_BaseConfigs","CUP_BaseData","CUP_WheeledVehicles_Core","CUP_TrackedVehicles_Core","CUP_AirVehicles_Core","CUP_WaterVehicles_Core","CUP_Vehicles_CfgGroups","CUP_AirVehicles_A10","CUP_AirVehicles_AH1Z","CUP_AirVehicles_AH64","CUP_AirVehicles_AV8B","CUP_AirVehicles_AW159","CUP_AirVehicles_C130J","CUP_AirVehicles_CH47","CUP_AirVehicles_CH53E","CUP_AirVehicles_DC3","CUP_AirVehicles_F35","CUP_AirVehicles_HC3","CUP_AirVehicles_Ka50","CUP_AirVehicles_MH60S","CUP_AirVehicles_Mi6","CUP_AirVehicles_Mi8","CUP_AirVehicles_Mi24","CUP_AirVehicles_MQ9","CUP_AirVehicles_MV22","CUP_AirVehicles_SA330","CUP_AirVehicles_Su25","CUP_AirVehicles_Su34","CUP_AirVehicles_UH1H","CUP_AirVehicles_UH1Y","CUP_AirVehicles_UH60","CUP_TrackedVehicles_AAV","CUP_TrackedVehicles_BMP","CUP_TrackedVehicles_Bradley","CUP_TrackedVehicles_m1_abrams","CUP_TrackedVehicles_M113","CUP_TrackedVehicles_M270","CUP_TrackedVehicles_Sounds","CUP_TrackedVehicles_T34","CUP_TrackedVehicles_T55","CUP_TrackedVehicles_T72","CUP_TrackedVehicles_ZSU23","CUP_WaterVehicles_Fishing_Boat","CUP_WaterVehicles_LHD","CUP_WaterVehicles_RHIB","CUP_WaterVehicles_Seafox","CUP_WaterVehicles_Weapons","CUP_WaterVehicles_Zodiac","CUP_WheeledVehicles_BRDM2","CUP_WheeledVehicles_BTR60","CUP_WheeledVehicles_BTR90","CUP_WheeledVehicles_Datsun","CUP_WheeledVehicles_Dingo","CUP_WheeledVehicles_HMMWV","CUP_WheeledVehicles_Jackal","CUP_WheeledVehicles_LAV25","CUP_WheeledVehicles_LR","CUP_WheeledVehicles_M1030","CUP_WheeledVehicles_Octavia","CUP_WheeledVehicles_RG31","CUP_WheeledVehicles_Skoda","CUP_WheeledVehicles_Stryker","CUP_WheeledVehicles_SUV","CUP_WheeledVehicles_TowingTractor","CUP_WheeledVehicles_UAZ","CUP_WheeledVehicles_Ural","CUP_WheeledVehicles_VWGolf"];};
if(isClass(configFile>>"cfgPatches">>"SFG_Tac_Beard"))then{
activateAddons["beard","beardasorted","beardsmall"];};};
_civs=paramsArray select 3;
_vDist=paramsArray select 6;
_rDir0=random 359;_rDir1=random 359;
_rFog0=switch(round(random 6))do{
case 0:{0 setFog 0.05};case 2:{0 setFog 0.1};case 3:{0 setFog 0.15};case 4:{0 setFog 0.2};case 5:{0 setFog 0.25};case 6:{0 setFog 0.3};case 7:{0 setFog 0.35};case 8:{0 setFog 0.4};};
_rFog1=switch(round(random 6))do{
case 0:{5400 setFog 0.05};case 2:{5400 setFog 0.1};case 3:{5400 setFog 0.15};case 4:{5400 setFog 0.2};case 5:{5400 setFog 0.25};case 6:{5400 setFog 0.3};case 7:{5400 setFog 0.35};};
0 setWindDir _rDir0;5400 setGusts 0.35;5400 setWindForce 0.35;5400 setWindStr 0.35;5400 setWindDir _rDir1;
if(!isClass(configFile>>"cfgPatches">>"ace_common"))then{
execVM "common\server\BWS\bulletWindServer.sqf";execVM "common\server\BWS\serverSync.sqf";};
if(isClass(configFile>>"cfgPatches">>"cba_main"))then{if(_civs==1)then{
#include "Civs\fn.sqf";
#include "Civs\List.sqf";
#include "Civs\BL.sqf";
[7,1200,2000]spawn L_fn_civs_spawnCivs;};};
civilian setFriend[west,1];civilian setFriend[east,1];civilian setFriend[independent,1];civilian setFriend[Resistance,1];
west setFriend[civilian,1];east setFriend[civilian,1];independent setFriend[civilian,1];Resistance setFriend[civilian,1];