
[_this, ["rhs_weap_hk416d10",
"rhs_weap_hk416d10_m320",
"rhs_weap_hk416d10_LMT",
"rhs_weap_hk416d145",
"rhs_weap_hk416d145_m320",
"rhs_weap_m14ebrri",
"rhs_weap_m16a4",
"rhs_weap_m16a4_carryhandle",
"rhs_weap_m16a4_carryhandle_M203",
"rhs_weap_m16a4_carryhandle_pmag",
"rhs_weap_m16a4_pmag",
"rhs_weap_XM2010",
"rhs_weap_XM2010_wd",
"rhs_weap_m24sws",
"rhs_weap_m240B",
"rhs_weap_m240B_CAP",
"rhs_weap_m240G",
"rhs_weap_m249_pip_L",
"rhs_weap_m249_pip_S_vfg",
"rhs_weap_m27iar",
"rhs_weap_m27iar_grip",
"rhs_weap_m4",
"rhs_weap_m4_carryhandle",
"rhs_weap_m4_carryhandle_pmag",
"rhs_weap_m4_carryhandle_mstock",
"rhs_weap_m4_m203",
"rhs_weap_m4_m320",
"rhs_weap_m4a1_m320",
"rhs_weap_m4_pmag",
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_m203S",
"rhs_weap_m4a1_blockII",
"rhs_weap_m4a1_blockII_KAC_bk",
"rhs_weap_m4a1_blockII_M203",
"rhs_weap_sr25",
"rhs_weap_sr25_ec_wd",
"rhs_weap_mk18_bk",
"rhs_weap_mk18_m320",
"rhs_weap_mk18_KAC_wd",
"hlc_lmg_M60E4",

"rhs_weap_fim92",
"rhs_weap_M136",
"rhs_weap_M136_hedp",
"rhs_weap_M136_hp",
"rhs_weap_m72a7",
"rhs_weap_smaw_green",
"rhs_weap_m249_pip",
"rhs_weap_m40a5",
"UK3CB_BAF_Javelin_Slung_Tube",
"UK3CB_BAF_Javelin_CLU",

"UK3CB_BAF_M6",
"UK3CB_BAF_WeaponsSecondary_AT4_CS_AT_Launcher", 
"UK3CB_BAF_WeaponsSecondary_AT4_CS_AP_Launcher",



"rhs_weap_M320",
"rhsusf_weap_m1911a1",
"rhsusf_weap_m9",
"rhsusf_weap_glock17g4"]] call BIS_fnc_addVirtualWeaponCargo;


[_this, ["rhs_mag_30Rnd_556x45_Mk262_Stanag",
"rhs_mag_30Rnd_556x45_M855A1_Stanag",
"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
"rhsusf_100Rnd_556x45_soft_pouch",
"rhsusf_20Rnd_762x51_m993_Mag",
"rhsusf_20Rnd_762x51_m62_Mag",
"rhsusf_5Rnd_300winmag_xm2010",
"rhsusf_5Rnd_762x51_m993_Mag",
"rhsusf_5Rnd_762x51_m62_Mag",
"rhsusf_100Rnd_762x51",
"rhsusf_100Rnd_762x51_m80a1epr",
"rhsusf_100Rnd_762x51_m62_tracer",
"rhsusf_100Rnd_762x51_m993",
"rhsusf_200Rnd_556x45_soft_pouch",
"rhs_200rnd_556x45_T_SAW",
"rhs_200rnd_556x45_M_SAW",
"rhs_200rnd_556x45_B_SAW",
"rhsusf_mag_17Rnd_9x19_JHP",
"rhsusf_mag_17Rnd_9x19_FMJ",
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_FMJ",
"rhsusf_mag_7x45acp_MHP",
"hlc_100Rnd_762x51_B_M60E4",
"hlc_100Rnd_762x51_T_M60E4",
"rhs_mag_smaw_SR",
"rhs_mag_smaw_HEDP",
"rhs_mag_smaw_HEAA",

"UK3CB_BAF_1Rnd_60mm_Mo_Shells", 
"UK3CB_BAF_1Rnd_60mm_Mo_Flare_White", 
"UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White",

"rhs_fim92_mag",


"rhs_mag_M441_HE",
"rhs_mag_M433_HEDP",
"rhs_mag_m714_White",
"rhs_mag_m715_Green",
"rhs_mag_m713_Red",
"rhs_mag_M585_white",
"rhs_mag_m662_red",
"rhs_mag_m661_green",
"rhs_mag_m4009",
"rhs_mag_m576",
"rhs_mag_an_m14_th3",
"rhs_mag_an_m8hc",
"rhs_mag_m18_green",
"rhs_mag_m18_red",
"rhs_mag_m67",
"ACE_M84",
"ACE_HuntIR_M203",
"B_IR_Grenade",
"Chemlight_green",
"ACE_Chemlight_HiOrange",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_IR",
"ACE_Chemlight_Shield",
"Laserbatteries",

"DemoCharge_Remote_Mag",
"ATMine_Range_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSBoundingMine_Range_Mag",
"SatchelCharge_Remote_Mag"]] call BIS_fnc_addVirtualMagazineCargo;


[_this, ["ACRE_PRC117F",
"ACRE_PRC148",
"ACRE_PRC152",
"ACRE_PRC343",
"ACE_RangeTable_82mm",
"ACE_ATragMX",
"ACE_fieldDressing",
"ACE_elasticBandage",
"ACE_quikclot",
"ACE_bloodIV_500",
"ACE_bodyBag",
"ACE_CableTie",
"ACE_DAGR",
"ACE_DefusalKit",
"ACE_EarPlugs",
"ACE_EntrenchingTool",
"ACE_epinephrine",
"ACE_Flashlight_MX991",
"ACE_HuntIR_monitor",
"ACE_IR_Strobe_Item",
"ACE_Kestrel4500",
"ACE_M26_Clacker",
"ACE_MapTools",
"ACE_microDAGR",
"ACE_morphine",
"ACE_packingBandage",
"ACE_personalAidKit",
"ACE_plasmaIV_250",
"ACE_RangeCard",
"ACE_salineIV_250",
"ACE_SpottingScope",
"ACE_tourniquet",
"ACE_surgicalKit",
"ACE_Sandbag_empty",
"ACE_Altimeter",
"ACE_SpraypaintBlack",
"ACE_SpraypaintBlue",
"ACE_SpraypaintGreen",
"ACE_SpraypaintRed",

"rhs_googles_black",
"Binocular",
"rhsusf_ANPVS_14",
"rhsusf_ANPVS_15",
"lerca_1200_tan",
"ACE_Vector",
"Laserdesignator",


"itemMap",
"ItemCompass",
"itemWatch",
"itemGPS",
"B_UavTerminal",
"ToolKit",
"ACE_Chemlight_Shield",


"rhsusf_acc_anpvs27",
"rhsusf_acc_ELCAN",
"rhsusf_acc_ACOG2",
"rhsusf_acc_ACOG",
"rhsusf_acc_eotech_552",
"rhsusf_acc_compm4",
"rhsusf_acc_premier_low",
"rhsusf_acc_premier_anpvs27",
"rhsusf_acc_premier",
"rhsusf_acc_LEUPOLDMK4",
"rhsusf_acc_LEUPOLDMK4_2",
"rhsusf_acc_SpecterDR_A",
"rhsusf_acc_eotech_xps3",
"rhsusf_acc_anpeq15side_bk",
"rhsusf_acc_nt4_black",
"rhsusf_acc_harris_bipod",
"rhsusf_acc_M2010S",
"rhsusf_acc_M8541",
"rhsusf_acc_ACOG_MDO",
"rhsusf_acc_ACOG_RMR",
"optic_LRPS",
"bipod_01_F_blk",
"ACE_wirecutter",
"ACE_UAVBattery",
"ACE_Tripod",
"rhs_weap_optic_smaw",

"rhsusf_ach_helmet_ocp",
"rhsusf_ach_helmet_ESS_ocp",
"rhsusf_ach_helmet_headset_ocp",
"rhsusf_ach_helmet_headset_ess_ocp",
"rhsusf_ach_helmet_camo_ocp",
"rhsusf_ach_helmet_ocp_norotos",
"rhs_uniform_cu_ocp",
"rhsusf_iotv_ocp_Grenadier",
"rhsusf_iotv_ocp_Medic",
"rhsusf_iotv_ocp",
"rhsusf_iotv_ocp_Repair",
"rhsusf_iotv_ocp_Rifleman",
"rhsusf_iotv_ocp_SAW",
"rhsusf_iotv_ocp_Squadleader",
"rhsusf_iotv_ocp_Teamleader"



]] call BIS_fnc_addVirtualItemCargo;


[_this, ["ace_gunbag",
"B_rhsusf_B_BACKPACK",
"B_AssaultPack_rgr",
"B_TacticalPack_blk",
"rhsusf_assault_eagleaiii_coy",
"rhsusf_assault_eagleaiii_ocp",
"rhsusf_falconii_coy",
"rhsusf_falconii_mc",
"rhsusf_falconii",
"ACE_SpareBarrel"


]] call BIS_fnc_addVirtualBackpackCargo;