class VAS {
	tag = "VAS";
	class functions {
		file = "scripts\VAS\functions";
		class onRespawn;
		class deleteGear;
		class loadoutInfo;
		class loadGear;
		class saveGear;
		class SaveLoad;
		class details;
		class removeGear;
		class addGear;
		class handleItem;
		class filterShow;
		class filterMenu;
		class fetchCfg;
		class fetchCfgDetails;
		class buildConfig;
		class filter;
		class fetchPlayerGear;
		class mainDisplay;
		class playerDisplay;
		class accType;
		class openDetails {};
		class closeDetails {};
		class quickMag {};
		class quickItem {};
		class qRemoveItem {};
		class mainInit {preInit = 1;};
		class KRON_StrLeft {};
		class KRON_StrToArray {};
		class accPrompt {};
		class quickAddDrag {};
		class updateLoad {};
		class transferMenu {};
		class transferAction {};
		class transferNetwork {};
		class transferSaveMenu {};
		class transferSaveGear {};
		class VASP {};
		class quickAttachment {};
		class accList {};
	};
};