with missionNamespace do {
	//--- Infantry
	EAST_SOLDIER = ["OP_Ren_01_brown", 1];
	EAST_SOLDIER_AA = ["OP_Ren_02_Med_brown", 1];
	EAST_SOLDIER_AR = ["OP_Ren_02_Eng_brown", 1];
	EAST_SOLDIER_AT = ["OP_Ren_01_AT_brown", 1];
	EAST_SOLDIER_CREW = ["OP_Ren_01_brown", 1];
	EAST_SOLDIER_LAT = ["OP_Ren_01_AT_brown", 1];
	EAST_SOLDIER_HAT = ["OP_Ren_01_AT_brown", 1];
	EAST_SOLDIER_ENGINEER = ["OP_Ren_01_brown", 1];
	EAST_SOLDIER_GL = ["OP_Ren_01_AT_brown", 1];
	EAST_SOLDIER_MEDIC = ["OP_Ren_01_brown", 1];
	EAST_SOLDIER_PILOT = ["OP_Ren_01_brown", 1];
	EAST_SOLDIER_SQUADLEADER = ["OP_Ren_01_brown", 1];
	EAST_SOLDIER_SNIPER = ["OP_Ren_01_brown", 1];
	EAST_SOLDIER_MARKSMAN = ["OP_Ren_01_brown", 1];
	EAST_SOLDIER_TEAMLEADER = ["OP_Ren_01_brown", 1];
	EAST_SOLDIER_HEAVYGUNNER = ["OP_Ren_01_brown", 1];
	
	//--- Vehicles
	EAST_MOTORIZED_MG = ["LRMKIV_possessed_0", 2];
	EAST_MOTORIZED_GL = ["LRMKIV_possessed_0", 2];

	//--- Infantry - Mixed
	EAST_SOLDIERS_MG_LIGHT = [EAST_SOLDIER_AR];
	EAST_SOLDIERS_MG_MEDIUM = [EAST_SOLDIER_AR, EAST_SOLDIER_HEAVYGUNNER];
	EAST_SOLDIERS_MG_HEAVY = [EAST_SOLDIER_HEAVYGUNNER, EAST_SOLDIER_HEAVYGUNNER];
	EAST_SOLDIERS_AT_LIGHT = [EAST_SOLDIER_LAT];
	EAST_SOLDIERS_AT_MEDIUM = [EAST_SOLDIER_AT];
	EAST_SOLDIERS_AT_HEAVY = [EAST_SOLDIER_HAT];
	EAST_SOLDIERS_SPECOPS = [["OP_Ren_01_brown", 1]];
	EAST_SOLDIERS_ENGINEER = [EAST_SOLDIER_ENGINEER, ["OP_Ren_01_brown", 1]];
	EAST_SOLDIERS_SNIPERS = [EAST_SOLDIER_SNIPER, ["OP_Ren_01_brown", 1], ["OP_Ren_01_brown", 1]];
	EAST_SOLDIERS_MARKSMEN = [EAST_SOLDIER_MARKSMAN, ["OP_Ren_01_brown", 1], ["OP_Ren_01_brown", 1]];

	//--- Vehicles
	EAST_VEHICLE_AA = [["LRMKIV_possessed_0", 1]];
	EAST_VEHICLE_APC = [["LRMKIV_possessed_0", 2], ["LRMKIV_possessed_0", 2]];
	// EAST_VEHICLE_ARMORED_HEAVY = ["armoheavy1","armoheavy2"];
	EAST_VEHICLE_ARMORED_LIGHT = [["LRMKIV_possessed_0", 2]];
	// EAST_VEHICLE_MECHANIZED = ["mechanized1","mechanized2"];
	EAST_VEHICLE_MOTORIZED = [EAST_MOTORIZED_MG, EAST_MOTORIZED_GL, EAST_MOTORIZED_MG];

	//--- Vehicles - Mixed
	EAST_VEHICLES_AA_LIGHT = EAST_VEHICLE_AA;
	// EAST_VEHICLES_LIGHT = EAST_VEHICLE_MECHANIZED + EAST_VEHICLE_MOTORIZED;
	EAST_VEHICLES_LIGHT = EAST_VEHICLE_MOTORIZED;
	EAST_VEHICLES_MEDIUM = EAST_VEHICLE_APC + EAST_VEHICLE_ARMORED_LIGHT;
	EAST_VEHICLES_HEAVY = EAST_VEHICLE_ARMORED_LIGHT;
};