with missionNamespace do {
	//--- Infantry
	WEST_SOLDIER = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_AA = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_AR = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_AT = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_CREW = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_LAT = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_HAT = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_ENGINEER = ["DKoK_Eng_1489th", 1];
	WEST_SOLDIER_GL = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_MEDIC = ["DKoK_Eng_1489th", 1];
	WEST_SOLDIER_PILOT = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_SQUADLEADER = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_SNIPER = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_MARKSMAN = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_TEAMLEADER = ["DKoK_GM_1489th", 1];
	WEST_SOLDIER_HEAVYGUNNER = ["DKoK_GM_1489th", 1];
	
	//--- Vehicles
	WEST_MOTORIZED_MG = ["Sentinel_HB_1490th_1", 2];
	WEST_MOTORIZED_GL = ["Sentinel_LC_1490th_1", 2];

	//--- Infantry - Mixed
	WEST_SOLDIERS_MG_LIGHT = [WEST_SOLDIER_AR];
	WEST_SOLDIERS_MG_MEDIUM = [WEST_SOLDIER_AR, WEST_SOLDIER_HEAVYGUNNER];
	WEST_SOLDIERS_MG_HEAVY = [WEST_SOLDIER_HEAVYGUNNER, WEST_SOLDIER_HEAVYGUNNER];
	WEST_SOLDIERS_AT_LIGHT = [WEST_SOLDIER_LAT];
	WEST_SOLDIERS_AT_MEDIUM = [WEST_SOLDIER_AT];
	WEST_SOLDIERS_AT_HEAVY = [WEST_SOLDIER_HAT];
	WEST_SOLDIERS_SPECOPS = [["DKoK_GM_1489th", 1]];
	WEST_SOLDIERS_SNIPERS = [WEST_SOLDIER_SNIPER, ["DKoK_GM_1489th", 1], ["DKoK_GM_1489th", 1]];
	WEST_SOLDIERS_MARKSMEN = [WEST_SOLDIER_MARKSMAN, ["DKoK_GM_1489th", 1], ["DKoK_GM_1489th", 1]];

	//--- Vehicles
	WEST_VEHICLE_AA = [["Sentinel_ML_1490th_1", 1]];
	WEST_VEHICLE_APC = [["_1490thChimAuto", 2], ["_1490thChimAuto", 2]];
	WEST_VEHICLE_ARMORED_HEAVY = [["LRMKIV_1490th_1", 2]];
	WEST_VEHICLE_ARMORED_LIGHT = [["LRMKIV_1490th_1", 2]];
	// WEST_VEHICLE_MECHANIZED = ["mechanized1","mechanized2"];
	WEST_VEHICLE_MOTORIZED = [WEST_MOTORIZED_MG, WEST_MOTORIZED_GL, WEST_MOTORIZED_MG];

	//--- Vehicles - Mixed
	WEST_VEHICLES_AA_LIGHT = WEST_VEHICLE_AA;
	// WEST_VEHICLES_LIGHT = WEST_VEHICLE_MECHANIZED + WEST_VEHICLE_MOTORIZED;
	WEST_VEHICLES_LIGHT = WEST_VEHICLE_MOTORIZED;
	WEST_VEHICLES_MEDIUM = WEST_VEHICLE_APC + WEST_VEHICLE_ARMORED_LIGHT;
	WEST_VEHICLES_HEAVY = WEST_VEHICLE_ARMORED_LIGHT + WEST_VEHICLE_ARMORED_HEAVY;
};