with missionNamespace do {
	//--- Infantry
	EAST_SOLDIER = ["LIB_SOV_LC_rifleman", 1];
	EAST_SOLDIER_AA = ["LIB_SOV_AT_soldier", 1];
	EAST_SOLDIER_AR = ["LIB_SOV_smgunner", 1];
	EAST_SOLDIER_AT = ["LIB_SOV_AT_grenadier", 1];
	EAST_SOLDIER_CREW = ["LIB_SOV_tank_crew", 1];
	EAST_SOLDIER_LAT = ["LIB_SOV_AT_grenadier", 1];
	EAST_SOLDIER_HAT = ["LIB_SOV_AT_soldier", 1];
	EAST_SOLDIER_ENGINEER = ["LIB_SOV_sapper", 1];
	EAST_SOLDIER_GL = ["LIB_SOV_rifleman", 1];
	EAST_SOLDIER_MEDIC = ["LIB_SOV_medic", 1];
	EAST_SOLDIER_PILOT = ["LIB_SOV_pilot", 1];
	EAST_SOLDIER_SQUADLEADER = ["LIB_SOV_captain", 1];
	EAST_SOLDIER_SNIPER = ["LIB_SOV_scout_sniper_autumn", 1];
	EAST_SOLDIER_MARKSMAN = ["LIB_SOV_scout_sniper_autumn", 1];
	EAST_SOLDIER_TEAMLEADER = ["LIB_SOV_first_lieutenant", 1];
	EAST_SOLDIER_HEAVYGUNNER = ["LIB_SOV_mgunner", 1];
	
	//--- Vehicles
	EAST_MOTORIZED_MG = ["LIB_Scout_M3_FFV", 2];
	EAST_MOTORIZED_GL = ["LIB_Scout_M3_FFV", 2];

	//--- Infantry - Mixed
	EAST_SOLDIERS_MG_LIGHT = [EAST_SOLDIER_AR];
	EAST_SOLDIERS_MG_MEDIUM = [EAST_SOLDIER_AR, EAST_SOLDIER_HEAVYGUNNER];
	EAST_SOLDIERS_MG_HEAVY = [EAST_SOLDIER_HEAVYGUNNER, EAST_SOLDIER_HEAVYGUNNER];
	EAST_SOLDIERS_AT_LIGHT = [EAST_SOLDIER_LAT];
	EAST_SOLDIERS_AT_MEDIUM = [EAST_SOLDIER_AT];
	EAST_SOLDIERS_AT_HEAVY = [EAST_SOLDIER_HAT];
	EAST_SOLDIERS_SPECOPS = [["LIB_SOV_AT_grenadier", 1]];
	EAST_SOLDIERS_ENGINEER = [EAST_SOLDIER_ENGINEER, ["LIB_SOV_sapper", 1]];
	EAST_SOLDIERS_SNIPERS = [EAST_SOLDIER_SNIPER, ["LIB_SOV_scout_sniper_autumn", 1], ["LIB_SOV_scout_sniper_autumn", 1]];
	EAST_SOLDIERS_MARKSMEN = [EAST_SOLDIER_MARKSMAN, ["LIB_SOV_scout_sniper_autumn", 1], ["LIB_SOV_scout_rifleman_autumn", 1]];

	//--- Vehicles
	EAST_VEHICLE_AA = [["LIB_SdKfz251_captured_FFV", 1]];
	EAST_VEHICLE_APC = [["LIB_Scout_M3", 2], ["LIB_SdKfz251_captured", 2]];
	// EAST_VEHICLE_ARMORED_HEAVY = ["armoheavy1","armoheavy2"];
	EAST_VEHICLE_ARMORED_LIGHT = [["LIB_T34_76", 2]];
	// EAST_VEHICLE_MECHANIZED = ["mechanized1","mechanized2"];
	EAST_VEHICLE_MOTORIZED = [EAST_MOTORIZED_MG, EAST_MOTORIZED_GL, EAST_MOTORIZED_MG];

	//--- Vehicles - Mixed
	EAST_VEHICLES_AA_LIGHT = EAST_VEHICLE_AA;
	// EAST_VEHICLES_LIGHT = EAST_VEHICLE_MECHANIZED + EAST_VEHICLE_MOTORIZED;
	EAST_VEHICLES_LIGHT = EAST_VEHICLE_MOTORIZED;
	EAST_VEHICLES_MEDIUM = EAST_VEHICLE_APC + EAST_VEHICLE_ARMORED_LIGHT;
	EAST_VEHICLES_HEAVY = EAST_VEHICLE_ARMORED_LIGHT;
};