with missionNamespace do {
	//--- Infantry
	GUER_SOLDIER = "LIB_FFI_Soldier_1";
	GUER_SOLDIER_AA = "LIB_FFI_Soldier_2";
	GUER_SOLDIER_AR = "LIB_FFI_Soldier_3";
	GUER_SOLDIER_AT = "LIB_FFI_Soldier_2";
	GUER_SOLDIER_CREW = "LIB_FFI_Soldier_5";
	GUER_SOLDIER_LAT = "LIB_FFI_Soldier_2";
	GUER_SOLDIER_HAT = "LIB_FFI_Soldier_2";
	GUER_SOLDIER_ENGINEER = "LIB_FFI_Soldier_3";
	GUER_SOLDIER_GL = "LIB_FFI_Soldier_4";
	GUER_SOLDIER_MEDIC = "LIB_FFI_Soldier_5";
	GUER_SOLDIER_PILOT = "LIB_FFI_Soldier_5";
	GUER_SOLDIER_SQUADLEADER = "LIB_FFI_Soldier_2";
	GUER_SOLDIER_SNIPER = "LIB_FFI_Soldier_3";
	GUER_SOLDIER_MARKSMAN = "LIB_FFI_Soldier_4";
	GUER_SOLDIER_TEAMLEADER = "LIB_FFI_Soldier_5";

	//--- Infantry - Mixed
	GUER_SOLDIERS_MG = [GUER_SOLDIER_AR];
	GUER_SOLDIERS_AT_LIGHT = [GUER_SOLDIER_LAT];
	GUER_SOLDIERS_AT_MEDIUM = [GUER_SOLDIER_AT];
	GUER_SOLDIERS_AT_HEAVY = [GUER_SOLDIER_HAT];
	GUER_SOLDIERS_SPECOPS = ["LIB_FFI_Soldier_3"];
	GUER_SOLDIERS_ENGINEER = [GUER_SOLDIER_ENGINEER, "LIB_FFI_Soldier_3"];
	GUER_SOLDIERS_SNIPERS = [GUER_SOLDIER_SNIPER, "LIB_FFI_Soldier_4", "LIB_FFI_Soldier_2"];
	GUER_SOLDIERS_MARKSMEN = [GUER_SOLDIER_MARKSMAN, GUER_SOLDIER_MARKSMAN, "LIB_FFI_Soldier_3"];

	//--- Vehicles
	GUER_VEHICLE_APC = ["LIB_GazM1_FFI"]; //todo: replace with real veh later on
	//GUER_VEHICLE_APC = [["I_APC_Wheeled_03_cannon_F"],["I_APC_tracked_03_cannon_F"]]; //todo: replace with real veh later on
	// GUER_VEHICLE_APC = ["LIB_SdKfz251_FFV", "LIB_Scout_M3", "LIB_SdKfz251", "LIB_Scout_M3"]; //todo: replace with real veh later on
	GUER_VEHICLE_ARMORED_HEAVY = ["LIB_GazM1_FFI"];
	GUER_VEHICLE_ARMORED_LIGHT = ["LIB_GazM1_FFI"];
	// GUER_VEHICLE_MECHANIZED = ["mechanized1","mechanized2"];
	GUER_VEHICLE_MOTORIZED = ["LIB_GazM1_FFI"];

	//--- Vehicles - Mixed
	// GUER_VEHICLES_AA_LIGHT = GUER_VEHICLE_AA;
	// GUER_VEHICLES_LIGHT = GUER_VEHICLE_MECHANIZED + GUER_VEHICLE_MOTORIZED;
	GUER_VEHICLES_LIGHT = GUER_VEHICLE_MOTORIZED;
	GUER_VEHICLES_MEDIUM = GUER_VEHICLE_ARMORED_LIGHT + GUER_VEHICLE_APC;
	//GUER_VEHICLES_MEDIUM = GUER_VEHICLE_APC;
	// GUER_VEHICLES_MEDIUM = GUER_VEHICLE_MOTORIZED;
	GUER_VEHICLES_HEAVY = GUER_VEHICLE_ARMORED_HEAVY;
};