if (!isServer) exitWith {};
_box = _this select 0;

while {alive _box} do {
	clearMagazineCargoGlobal _box;
	clearWeaponCargoGlobal _box;
	clearItemCargoGlobal _box;
	_box addweaponCargoGlobal ["arifle_Khaybar_F", 2];
	_box addweaponCargoGlobal ["arifle_Khaybar_C_F", 2];
	_box addweaponCargoGlobal ["arifle_Khaybar_GL_F", 2];
	_box addweaponCargoGlobal ["hgun_rook40_F", 2];
	_box addWeaponCargoGlobal ["LMG_Mk200_F", 1];
	_box addMagazineCargoGlobal ["30Rnd_65x39_caseless_green", 50];
	_box addMagazineCargoGlobal ["30Rnd_65x39_caseless_green_mag_Tracer", 50];
	_box addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag", 50];
	_box addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag_Tracer", 50];
	_box addMagazineCargoGlobal ["100Rnd_65x39_caseless_mag", 50];
	_box addMagazineCargoGlobal ["100Rnd_65x39_caseless_mag_Tracer", 50];
	_box addMagazineCargoGlobal ["20Rnd_762x45_mag", 50];
	_box addMagazineCargoGlobal ["20Rnd_556x45_UW_mag", 50];
	_box addMagazineCargoGlobal ["30Rnd_556x45_Stanag", 50];
	_box addMagazineCargoGlobal ["30Rnd_65x39_case_mag", 50];
	_box addMagazineCargoGlobal ["30Rnd_65x39_case_mag_Tracer", 50];
	_box addMagazineCargoGlobal ["16Rnd_9x21_Mag", 50];
	_box addMagazineCargoGlobal ["30Rnd_9x21_Mag", 50];
	_box addMagazineCargoGlobal ["200Rnd_65x39_cased_Box", 50];
	_box addMagazineCargoGlobal ["200Rnd_65x39_cased_Box_Tracer", 50];
	_box addweaponCargoGlobal ["launch_RPG32_F",1];
	_box addmagazineCargoGlobal ["RPG32_F", 1];
	_box addmagazineCargoGlobal ["ClaymoreDirectionalMine_Remote_Mag", 2];
	_box addmagazineCargoGlobal ["DemoCharge_Remote_Mag", 2];
	_box addmagazineCargoGlobal ["1Rnd_HE_Grenade_shell", 3];
	_box addmagazineCargoGlobal ["SmokeShellRed", 3];
	_box additemCargoGlobal ["Zasleh2",2]; 
	_box additemCargoGlobal ["muzzle_snds_H", 2];  
	_box additemCargoGlobal ["muzzle_snds_L", 2];  
	_box additemCargoGlobal ["muzzle_snds_B", 2];  
	_box additemCargoGlobal ["muzzle_snds_H_MG", 2];  
	_box additemCargoGlobal ["optic_Arco", 2];  
	_box additemCargoGlobal ["optic_Hamr", 2];  
	_box additemCargoGlobal ["optic_Aco", 2];  
	_box additemCargoGlobal ["optic_ACO_grn",2];  
	_box additemCargoGlobal ["optic_Holosight", 2]; 
	_box additemCargoGlobal ["acc_flashlight", 2];  
	_box additemCargoGlobal ["acc_pointer_IR", 2];
	sleep 300;
};